auth-server: http://auth.ailikes.com:5000/uc # 认证服务器地址

server:
  domain: http://sso.ailikes.com
  session:
    cookie:
      name: CLIENTSESSION
  port: 8085
  servlet:
    context-path: /sso
management:
  security:
    enabled: false
  server:
    servlet:
      context-path: /mgmt
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: sso-service
      client-secret: password
      scope: server
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri: ${auth-server}/user
      check-token-access: ${auth-server}/oauth/check_token
#注册中心
eureka:
  instance:
    hostname: registry.junxinweike.club
    prefer-ip-address: true
    health-check-url-path: ${server.servlet.context-path}${management.server.servlet.context-path}/health
    status-page-url-path: ${server.servlet.context-path}${management.server.servlet.context-path}/info
    metadata-map:
      management.context-path: ${server.servlet.context-path}${management.server.servlet.context-path}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry.junxinweike.club:8761/eureka/
  #安全配置
  security:
    ignored: /css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico,/static/**,/public/**,/api/swagger-ui.html,/swagger-ui.html,/v2/api-docs, /configuration/ui,/swagger-resources

#数据源配置
spring:
  rabbitmq:
    host: mq.junxinweike.club
    sleuth:
      sampler:
        percentage: 1
      integration:
        enabled: false
      scheduled:
        skip-pattern: "^org.*HystrixStreamTask$"
  datasource:
    url: jdbc:mysql://111.207.248.45:3306/jiajiaozaixian_dev?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiuaiNI0523
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    show-sql: true
  # thymeleaf:
  #   prefix: classpath:/templates/
  freemarker:
    suffix: .html # 设置模板后缀名
    content-type: text/html # 设置文档类型
    charset: UTF-8                               # 设置页面编码格式
    cache: false                                 # 设置页面缓存
    template-loader-path: classpath:/templates # 设置ftl文件路径
    mvc:
      static-path-pattern: /static # 设置静态文件路径，js,css等
#swagger接口配置
swagger:
  base-package: com.ailikes.sso

